import type { Metadata } from 'next'
import { Space_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '../components/ui/navbar'

const space_mono = Space_Mono({
  weight: ['400', '700'],
  subsets: ['latin'],
  style: ['normal'],
  display: 'swap',
  variable: '--font-space_mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${space_mono.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
